### ISSUE TITLE
Drop PHP 5.3 and Add Namespaces?

### ISSUE THREAD

**Issue by vinkla** [keyvanakbary/slugifier#10]
What about dropping PHP 5.3 support and add namespaces with PSR-4 autoloading? PHP 5.4 will no longer be maintained from september 2015.

**Comment by keyvanakbary** [comment]
Namespaces are supported since PHP 5.3 and this library [already has PSR-4 autoloading](https://github.com/keyvanakbary/slugifier/blob/master/composer.json#L20). I support PHP 5.3 for old clients. The tradeoff between dropping versions and adding new language features, is not worthy yet.
If you've read the documentation, this library operates under the root namespace, that's why you have to type `/Slugifier`. I didn't want to complicate things nesting namespaces, the uniqueness of the name is enough for avoiding collisions.
I'll definitively bump the PHP version requirements in the near future, but it will not be because of namespaces. Probably, I'll move towards a more functional approach. There's no point to have a class without state, this should be just pure functions.

Thanks again for your effort :)
