### ISSUE TITLE
Multibyte string fucntions

### ISSUE THREAD

**Issue by neo22s** [keyvanakbary/slugifier#13]
Should you use http://php.net/manual/en/function.mb-strtolower.php ?

The rest looks really good! love the functional approach and simplicity.

Where did you get the const CHAR_MAP ?

I also think will work on PHP 5.4. I say this since many hosting companies are not updated :S

**Comment by neo22s** [comment]
Ok, just saw why you do not use mb_ you replace the special chars first so no need to use the mb_ since the text is good already ;)

cool!

**Comment by keyvanakbary** [comment]
Hey, thanks man :)

Constants with array values are supported only by PHP 5.6 and above and is not compatible with HHVM. That's why I've created two separate versions for it [v3.0.0](https://github.com/keyvanakbary/slugifier/releases/tag/v3.0.0) with support for PHP 5.3 to 7 & HHVM and [v4.0.0](https://github.com/keyvanakbary/slugifier/releases/tag/v4.0.0) with a cleaner design but limited to PHP 5.6 and 7 :)

Cheers!

**Comment by neo22s** [comment]
Beautiful! https://github.com/keyvanakbary/slugifier/blob/v3.0.0/src/slugifier.php

We will probably use it on https://github.com/open-classifieds/openclassifieds2 and of course credit you.

thanks ;)

**Comment by neo22s** [comment]
Mostly we had same solution but missing all this chars_map! :D

**Comment by keyvanakbary** [comment]
@neo22s Thanks man, you make me happy ::))
